service: python-rest-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-south-1

package:
  # exclude deprecated
  exclude: 
    - test.py

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  
  dummyGet:
    handler: handler.get_dummy_data
    events:
      - http:
          path: /test
          method: get

plugins:
  - serverless-python-requirements
